apiVersion: v1
kind: Service
metadata:
  name: sudonet-service
  labels:
    app: sudonet
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    - port: 80
      nodePort: 30180
      name: http
    - port: 443
      nodePort: 31443
      name: https
  selector:
    app: sudonet